TRAIN:
  train_batch_size: 8
  lr: 0.0001

  valid_batch_size: 8

  image_size: [224,224]

  min_epochs: 20
  max_epochs: 100
  patience: 20

  device: 1

  model_save_path: ./save_model
  model_save_filename: medseg

MODEL:
  bert_type: microsoft/BiomedVLP-CXR-BERT-specialized
  vision_type1: facebook/convnext-tiny-224
  vision_type2: microsoft/swin-tiny-patch4-window7-224
  project_dim: 768

DATA:
  train_csv_path: /home/sakir-w4-linux/Development/Thesis/CIBM/Datasets/MosMedData+/Ariadne/Train Set/Train_text_MosMedData+ 1.csv
  train_root_path: /home/sakir-w4-linux/Development/Thesis/CIBM/Datasets/MosMedData+/Ariadne/Train Set

  test_csv_path: /home/sakir-w4-linux/Development/Thesis/CIBM/Datasets/MosMedData+/Ariadne/Test Set/Test_text_MosMedData+.csv
  test_root_path: /home/sakir-w4-linux/Development/Thesis/CIBM/Datasets/MosMedData+/Ariadne/Test Set