TRAIN:
  train_batch_size: 4
  lr: 0.0003

  valid_batch_size: 4

  image_size: [224,224]

  min_epochs: 20
  max_epochs: 200
  patience: 20

  device: 1

  model_save_path: ./save_model
  model_save_filename: convNext-UnetR

MODEL:
  bert_type: microsoft/BiomedVLP-CXR-BERT-specialized
  vision_type1: facebook/convnext-tiny-224
  project_dim: 768

DATA:
  train_csv_path: /home/sakir-w4-linux/Development/Thesis/CIBM/Datasets/Synapse/Ariadne/Train Set/synapse_npz_200.csv
  train_root_path: /home/sakir-w4-linux/Development/Thesis/CIBM/Datasets/Synapse/Ariadne/Train Set

  test_csv_path: /home/sakir-w4-linux/Development/Thesis/CIBM/Datasets/Synapse/Ariadne/Test Set/synapse_h5_200.csv
  test_root_path: /home/sakir-w4-linux/Development/Thesis/CIBM/Datasets/Synapse/Ariadne/Test Set